### ISSUE TITLE
browser() called from priorGraph

### ISSUE THREAD

**Issue by sempwn** [rjbgoudie/structmcmc#1]
The `browser()` function is called inside the priorGraph function, meaning that Rstudio breaks and won't continue until enter is pressed. As this function is called many times I've not been able to run the example code given [here](https://gist.github.com/rjbgoudie/970279)

Section of code is below:

```R
  difference <- setdiff(x, graph[[i]])
  difference <- length(difference)
  browser()
  exp(-lambda * difference)
```

RStudio Version 1.1.419

**Comment by rjbgoudie** [comment]
Thanks for the report. 46f81caee4e355cacbd2795f9ae42f750e98c95d removes the browser() call. Hopefully that fixes your problem.

**Comment by sempwn** [comment]
Thanks for the quick response @rjbgoudie - that works.
