### ISSUE TITLE
gibbs

### ISSUE THREAD

**Issue by evanamartin** [rjbgoudie/structmcmc#3]
I get the popup window "R session aborted. R encountered a fatal error. The session was terminated." when I try to run the examples from the README file with the argument method = "gibbs". Do I need to change the other arguments when methods = "gibbs"?

I am running R version 3.5.0

**Comment by rjbgoudie** [comment]
Thank you very much for the report. A couple of changes in dependencies caused the problems: in fastmatch (05c433d169b13e83f6782e4cb23df767c7c37b1f) and bit (582c4b9354a7f2720b61e339a602a785a6905da0). Basic running should now work. Let me know if you have further problems.

**Comment by evanamartin** [comment]
The "gibbs" option is working  on each of my systems. Thank you very much.
